apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: 616222093056.dkr.ecr.us-east-2.amazonaws.com/flaskapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancers
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-svc
spec:
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: LoadBalancer
